apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: url-shortener
type: Opaque
stringData:
  POSTGRES_USER: ronitboddu
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: postgres
  DB_USER: ronitboddu
  DB_PASSWORD: postgres
  DB_NAME: postgres