upstream db_server {
    server db-service1:8000;
    server db-service2:8000;
    server db-service3:8000;
}

server {
    listen 8000;

    location / {
        proxy_pass http://db_server;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
